services:
  blitz-login:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: